[project]
name = "Backend Test Github API Integration"
version = "0.1.0"
description = "A backend Github API integration test from cactro.com"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "requests>=2.32.3",
]
